# Generated by Django 4.0.4 on 2022-05-11 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='marketitem',
            options={'verbose_name': 'Market Item', 'verbose_name_plural': 'Market Items'},
        ),
        migrations.AddField(
            model_name='marketitem',
            name='item_freeze_quantity',
            field=models.BooleanField(default=False),
        ),
    ]
